# Generated by Django 3.2.6 on 2021-08-31 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='photo',
            field=models.ImageField(max_length=1000, upload_to='frontend/static/images'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=100, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='', max_length=50, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='', max_length=50, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='school',
            field=models.CharField(default='', max_length=50, verbose_name='school'),
        ),
    ]
